name: ressengaer_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  provider: ^6.0.1
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  cloud_firestore: ^3.1.5
  firebase_database: ^8.0.0
  firebase_storage: ^10.0.5
  firebase_core: ^1.7.0
  permission_handler: ^8.1.6



  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  firebase_auth: ^3.3.4
  awesome_dialog: ^2.1.2
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.2.0
  flutter_rating_bar: ^4.0.0
  location: ^4.3.0
  carousel_slider: ^4.0.0
  multiselect: ^0.0.4
  flutter_launcher_icons: ^0.9.2
  convex_bottom_bar: ^3.0.0



dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

#flutter_icons:
#  image_path: "assets/images/logo.png"
#  android: true
#  ios: true
#  adaptive_icon_foreground: "assets/images/logo2.png"
#  adaptive_icon_background: "#ffffff"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Mont
     fonts:
       - asset: assets/fonts/Montserrat-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
